# Server
server.port=${PORT:8080}

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# App
app.base-url=${APP_BASE_URL:http://localhost:8080}

# Database
spring.datasource.url=${DB_URL}
spring.datasource.driverClassName=${DB_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

resend.api.key=re_K8fRmLq7_FxJtFZbGpAwB5Hg4qrXFjnwW
app.mail.from=${MAIL_FROM:onboarding@resend.dev}

# Admin Bootstrap
app.admin.username=${ADMIN_USERNAME}
app.admin.email=${ADMIN_EMAIL}
app.admin.default-password=${ADMIN_PASSWORD}