# Server
server.port=${PORT}

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS}

# App
app.base-url=${APP_BASE_URL}

# Database
spring.datasource.url=${DB_URL}
spring.datasource.driverClassName=${DB_DRIVER_CLASS_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.show-sql=${JPA_SHOW_SQL}
spring.jpa.open-in-view=${JPA_OPEN_IN_VIEW}
spring.jpa.properties.hibernate.dialect=${JPA_HIBERNATE_DIALECT}

# Mail
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${RESEND_API_KEY}

spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS_ENABLE}
spring.mail.properties.mail.smtp.starttls.required=${MAIL_STARTTLS_REQUIRED}
spring.mail.properties.mail.smtp.ssl.enable=${MAIL_SSL_ENABLE}
spring.mail.properties.mail.smtp.connectiontimeout=${MAIL_CONNECTION_TIMEOUT}
spring.mail.properties.mail.smtp.timeout=${MAIL_TIMEOUT}
spring.mail.properties.mail.smtp.writetimeout=${MAIL_WRITE_TIMEOUT}
spring.mail.properties.mail.debug=${MAIL_DEBUG}
app.mail.from=${MAIL_FROM}

# Admin Bootstrap
app.admin.username=${ADMIN_USERNAME}
app.admin.email=${ADMIN_EMAIL}
app.admin.default-password=${ADMIN_PASSWORD}
