# Server
server.port=${PORT:8080}

# JWT
app.jwt.secret=${JWT_SECRET:VGhpc0lzQVN1cGVyU2VjdXJlSldUU2VjcmV0S2V5VGhhdENoYW5nZUlOUnVuVGltZQ==}
app.jwt.expiration-ms=3600000

# App
app.base-url=${APP_BASE_URL:https://bmb-production-936f.up.railway.app}

# Database
spring.datasource.url=${DB_URL:jdbc:mysql://viaduct.proxy.rlwy.net:39532/railway}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:wMnNsEmfWtWyrpSpLMzgWGeWSPqBbvMd}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Mail
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=${MAIL_FROM:${MAIL_USERNAME}}

# Admin Bootstrap
app.admin.username=${ADMIN_USERNAME:admin}
app.admin.email=${ADMIN_EMAIL:admin@college.com}
app.admin.default-password=${ADMIN_PASSWORD:Admin@123}