package com.example.demo.entity;

public enum Permission {
    CREATE_SESSION,
    LOCK_SESSION,
    APPROVE_SESSION,
    CANCEL_SESSION,
    MANUAL_MARK_ATTENDANCE,
    VIEW_OWN_ATTENDANCE,
    VIEW_SECTION_ATTENDANCE,
    VIEW_DEPARTMENT_ANALYTICS,
    MANAGE_USERS,
    ASSIGN_TEACHER_SECTION,
    ASSIGN_CLASS_TEACHER
}
